Add everything
fluture-js/fluenture pull request #1
Opened 2019-06-07 09:44 UTC by Avaq

For the nostalgic developer

2019-11-01 15:19 UTC, dicearr requested changes

2019-11-01 15:19 UTC, dicearr commented on index.js
> +//. once exception; If a Future is returned from the given function, it is
```suggestion
//. one exception; If a Future is returned from the given function, it is
```

2019-11-01 15:19 UTC, dicearr commented on index.js
> +//. Fluent [`alt`](https://github.com/fluture-js/Fluture#alt).
```suggestion
//. Fluent [`alt`](https://github.com/fluture-js/Fluture#alt)
```

2019-11-01 15:19 UTC, dicearr commented on index.js
> +//. Fluent [`and`](https://github.com/fluture-js/Fluture#and).
```suggestion
//. Fluent [`and`](https://github.com/fluture-js/Fluture#and)
```

2019-11-01 15:19 UTC, dicearr commented on index.js
> +//. Fluent [`ap`](https://github.com/fluture-js/Fluture#ap).
```suggestion
//. Fluent [`ap`](https://github.com/fluture-js/Fluture#ap)
```

2019-11-01 15:19 UTC, dicearr commented on rollup.config.js
> +    format: 'cjs',
This would mean that browser users are forced to use ESM and deeply import from `index.js`. Wouldn't it be better to set the format to `umd`?

2019-11-01 15:49 UTC, Avaq commented on rollup.config.js
> +    format: 'cjs',
Oh no!

2019-11-17 09:49 UTC, Avaq commented on rollup.config.js
> +    format: 'cjs',
Updated.

2019-11-17 12:32 UTC, dicearr approved these changes

2019-11-17 20:00 UTC, merged